# Generated by Django 3.2.15 on 2022-09-09 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Work in progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold'), ('RETIRED', 'Retired')], default='IN_PROGRESS', max_length=50, verbose_name='status')),
                ('desciption', models.TextField(blank=True, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(db_index=True, verbose_name='start date')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('starttime', models.TimeField(blank=True, db_index=True, null=True, verbose_name='start time')),
                ('endtime', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('wordcount', models.IntegerField(blank=True, null=True, verbose_name='word count')),
                ('activity', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='activity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wordtracker.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'work session',
                'verbose_name_plural': 'work sessions',
            },
        ),
    ]
