# Generated by Django 3.2.17 on 2023-02-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Work in progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold'), ('RETIRED', 'Retired')], default='IN_PROGRESS', help_text='Note: Only Works In Progress will be selectable in new work sessions.', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='project',
            field=models.ForeignKey(blank=True, help_text="Don't worry, you can add a project later or change this value.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='wordtracker.project', verbose_name='project'),
        ),
    ]
